import Header from "./_components/header";

import favicon from "./favicon.ico"

import type { Metadata } from "next";
import localFont from "next/font/local";
import "../../styles/globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "KitsuneProgrammer",
  description: "Generated by create next app",
  icons: favicon.src
};

export default function RootLayout({children,}: Readonly<{children: React.ReactNode;}>) {
  return (
    <html lang="ja">

      <body>
        <Header/>
        <main>
          <div className="article">{children}</div>
          <div className="side"></div>
        </main>
      </body>
    </html>
  );
}