import type { Metadata } from "next";
import "./globals.css";
import Header from "./_components/header";

export const metadata: Metadata = {
  title: "KitsuneProgrammer",
  description: "Generated by create next app",
};

export default function RootLayout({children}: Readonly<{children: React.ReactNode;}>) {
  return (
    <html lang="ja">
      <head>
        <link rel="icon" href="./favicon.ico"/>
      </head>
      <body>
        <Header/>
        <main>
          {children}
        </main>
      </body>
    </html>
  );
}